# Generated by Django 4.1.5 on 2023-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SourceCode',
            field=models.FileField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='Text',
            field=models.TextField(max_length=1000),
        ),
    ]
